"""
strategies/base.py
──────────────────
Base class that all strategies inherit from.
Defines the signal interface and common utilities.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional
import pandas as pd


class SignalType(Enum):
    BUY  = "BUY"
    SELL = "SELL"
    NONE = "NONE"


@dataclass
class Signal:
    """
    Represents a trading signal generated by a strategy.
    Passed through the consensus engine and then to the trader/telegram.
    """
    strategy:   str                     # which strategy fired this
    symbol:     str                     # e.g. "BTC/USDT"
    signal:     SignalType              # BUY | SELL | NONE
    entry:      float  = 0.0           # suggested entry price
    stop_loss:  float  = 0.0           # calculated stop loss
    take_profit1: float = 0.0          # first target
    take_profit2: float = 0.0          # second target
    confidence: str    = "MEDIUM"      # LOW | MEDIUM | HIGH
    timeframe:  str    = "4h"
    reason:     str    = ""            # human readable explanation
    timestamp:  Optional[pd.Timestamp] = None

    def is_valid(self) -> bool:
        return (
            self.signal != SignalType.NONE
            and self.entry > 0
            and self.stop_loss > 0
            and self.take_profit1 > 0
        )

    def risk_reward(self) -> float:
        """Calculate actual R:R ratio for this signal."""
        if self.signal == SignalType.BUY:
            risk   = self.entry - self.stop_loss
            reward = self.take_profit1 - self.entry
        else:
            risk   = self.stop_loss - self.entry
            reward = self.entry - self.take_profit1

        if risk <= 0:
            return 0.0
        return round(reward / risk, 2)


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    Each strategy must implement the `generate_signal` method.
    """

    name: str = "BaseStrategy"

    def __init__(self, params: dict):
        self.params = params

    @abstractmethod
    def generate_signal(self, df: pd.DataFrame, symbol: str) -> Signal:
        """
        Analyse the OHLCV DataFrame and return a Signal.

        Args:
            df:     OHLCV DataFrame with indicators already computed
            symbol: trading pair string e.g. "BTC/USDT"

        Returns:
            Signal object (signal=NONE if no trade)
        """
        ...

    # ── Shared helpers ─────────────────────────────────────────────────────────

    def _latest(self, df: pd.DataFrame, col: str, shift: int = 0):
        """Get the most recent (or shifted) value from a column."""
        return df[col].iloc[-(1 + shift)]

    def _prev(self, df: pd.DataFrame, col: str):
        """Get the second-to-last value (previous candle)."""
        return self._latest(df, col, shift=1)

    def _crossover(self, series_a: pd.Series, series_b: pd.Series) -> bool:
        """True if series_a crossed ABOVE series_b in last 2 candles."""
        for i in range(1, 3):
          if (series_a.iloc[-(i+1)] <= series_b.iloc[-(i+1)]) and \
           (series_a.iloc[-i] > series_b.iloc[-i]):
            return True
        return False

    def _crossunder(self, series_a: pd.Series, series_b: pd.Series) -> bool:
         """True if series_a crossed BELOW series_b in last 2 candles."""
         for i in range(1, 3):
           if (series_a.iloc[-(i+1)] >= series_b.iloc[-(i+1)]) and \
           (series_a.iloc[-i] < series_b.iloc[-i]):
            return True
         return False

    def _atr_sl_tp(
        self,
        df: pd.DataFrame,
        signal: SignalType,
        entry: float,
        atr_mult_sl: float = 1.5,
        tp1_rr: float = 1.5,
        tp2_rr: float = 3.0,
    ) -> tuple[float, float, float]:
        """
        Calculate stop loss and take profits using ATR.
        Returns: (stop_loss, take_profit1, take_profit2)
        """
        atr = self._latest(df, "ATRr_14") if "ATRr_14" in df.columns else (entry * 0.01)
        risk = atr * atr_mult_sl

        if signal == SignalType.BUY:
            sl  = entry - risk
            tp1 = entry + (risk * tp1_rr)
            tp2 = entry + (risk * tp2_rr)
        else:
            sl  = entry + risk
            tp1 = entry - (risk * tp1_rr)
            tp2 = entry - (risk * tp2_rr)

        return round(sl, 4), round(tp1, 4), round(tp2, 4)

    def no_signal(self, symbol: str) -> Signal:
        """Convenience: return a NONE signal."""
        return Signal(
            strategy=self.name,
            symbol=symbol,
            signal=SignalType.NONE,
        )
    
    
